// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DDona.KrunkDS.Data
{

    // Role
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Role
    {
        public int Id { get; set; } // Id (Primary key)
        public string Description { get; set; } // Description (length: 50)
        public bool IsActive { get; set; } // IsActive

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<User> User { get; set; } // User.FK_User_Role

        public Role()
        {
            User = new System.Collections.Generic.List<User>();
        }
    }

}
// </auto-generated>
