// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace DDona.KrunkDS.Data
{

    // Settings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Settings
    {
        public int Id { get; set; } // Id (Primary key)
        public string Module { get; set; } // Module (length: 20)
        public string Key { get; set; } // Key (length: 20)
        public string Value { get; set; } // Value (length: 80)
        public System.DateTime CreateDate { get; set; } // CreateDate
    }

}
// </auto-generated>
